/*
 * generated by Xtext 2.17.0
 */
package de.itemis.iap


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class IAPDSLStandaloneSetup extends IAPDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new IAPDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
