/*
 * generated by Xtext 2.17.0
 */
package de.itemis.iac.tests

import com.google.inject.Inject
import de.itemis.iac.iACDSL.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import static extension org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(IACDSLInjectorProvider)
class IACDSLParsingTest {
	@Inject
	extension ParseHelper<Model> parseHelper
	
	@Test
	def void loadEmptyModel() {
		''''''.parseAndValidate		
	}
	
	@Test
	def void loadSingleIssue() {
		'''issue single'''.parseAndValidate		
	}
	
	def void parseAndValidate(CharSequence it){
		val result = parse
		result.assertNotNull
		val errors = result.eResource.errors
		assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
