/*
 * generated by Xtext 2.17.0
 */
package de.itemis.iac.ide

import com.google.inject.Guice
import de.itemis.iac.IACDSLRuntimeModule
import de.itemis.iac.IACDSLStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class IACDSLIdeSetup extends IACDSLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new IACDSLRuntimeModule, new IACDSLIdeModule))
	}
	
}
