/*
 * generated by Xtext 2.17.0
 */
package de.itemis.iac.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class IACDSLProposalProvider extends AbstractIACDSLProposalProvider {
}
