/*
 * generated by Xtext 2.17.0
 */
package de.itemis.iac


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class IACDSLRuntimeModule extends AbstractIACDSLRuntimeModule {
}
