/*
 * generated by Xtext 2.17.0
 */
package de.itemis.iac


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class IACDSLStandaloneSetup extends IACDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new IACDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
