/*
 * generated by Xtext 2.17.0
 */
package de.itemis.iap.ide

import com.google.inject.Guice
import de.itemis.iap.IAPDSLRuntimeModule
import de.itemis.iap.IAPDSLStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class IAPDSLIdeSetup extends IAPDSLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new IAPDSLRuntimeModule, new IAPDSLIdeModule))
	}
	
}
